Traceback (most recent call last):
  File "main.py", line 434, in <module>
    "Top1 Accuracy": top1,
NameError: name 'top1' is not defined
Traceback (most recent call last):
  File "main.py", line 434, in <module>
    "Top1 Accuracy": top1,
NameError: name 'top1' is not defined